---
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Upgrade Packages
    apt:
      upgrade: yes
  - name: "install python for Ansible."
    apt:
      name: python3
      state: present
  - name: Configuring the timezone for nodejs
    shell: |
      ln -fs /usr/share/zoneinfo/Asia/Singapore /etc/localtime
  - name: Install tzdata
    apt:
      name: tzdata
      state: present
  - name: "Install nodejs and npm"
    apt:
      name: "{{ packages }} "
      state: present
    vars:
      packages:
      - nodejs
      - npm
  - name: Install pm2
    npm:
      name: pm2
      global: yes