route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-me'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'email-me'
  email_configs:
  - to: ernestvooncs@outlook.com
    from: popescape95@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: ernestvoon@ttyusb.dev
    auth_identity: ernestvoon@ttyusb.dev
    auth_password: tukcqbzwjivryczm
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
