---
  - name: Create the node_exporter user
    become: true
    shell: |
      useradd --no-create-home --shell /bin/false node_exporter
  - name: Download node_exporter module for Prometheus
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
      dest: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
  - name: Unarchive the node_exporter binary
    unarchive:
      src: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes
  - name: "move binary to /usr/local/bin."
    become: true
    copy:
      src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
      dest: /usr/local/bin
      mode: 744
      owner: node_exporter
      group: node_exporter
      remote_src: yes
  - name: Copy the node-exporter service file to systemd
    become: true
    copy:
      src: node-exporter.service
      dest: /etc/systemd/system/
      mode: 644
      owner: root
      group: root
  - name: Enable the services of Prometheus
    become: true
    shell: |
      systemctl daemon-reload
      systemctl start node-exporter
      systemctl enable node-exporter